### ISSUE TITLE
Unable to run npm commands

### ISSUE THREAD

**Issue by kyleect** [davezuko/react-redux-starter-kit#1]
I've freshly clone the repo, ran `npm install` and tried to run `npm run dev` and get this error:

> /home/devbox/dev/todo/build/webpack/client/index.js:49
      \`sass-loader?includePaths[]=${projectConfig.inSrc('styles')}\`
      ^
SyntaxError: Unexpected token ILLEGAL

It appears node doesn't support string templates even with `--harmony` flag. Perhaps I missed a step. I have node 0.12.7 installed via nvm running on ubuntu 14.04

**Comment by davezuko** [comment]
Hey this might just be my fault with specifying versions, as I haven't tested it outside of iojs in a while. Let me switch my nvm over and give it a shot. My bad!

**Comment by davezuko** [comment]
These configs used to be pre-processed with `babel/register` up until a few days ago, which is probably what caused this. I updated it to a normal string concatenation and was able to run the dev command successfully with node  0.12.2. Try updating your master branch and let me know if you're still having issues.

Sorry about that!

**Comment by jendiamond** [comment]
##### Having problems with `Ubuntu 14.04`, `npm version 2.14.4`,  `nodejs 4.1.1`
I need nodejs 4.1.1 to work on a project. Any ideas?

---

**This is my stack trace.**
```
$ npm start

> react-redux-starter-kit@0.15.1 start /vagrant/lingo-client-react
> npm run dev


> react-redux-starter-kit@0.15.1 dev /vagrant/lingo-client-react
> node --harmony bin/webpack-dev-server

module.js:338
    throw err;
    ^

Error: Cannot find module 'tapable'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/vagrant/lingo-client-react/node_modules/webpack/lib/Compiler.js:6:15)
    at Module._compile (module.js:434:26)
    at Module._extensions..js (module.js:452:10)
    at Object.require.extensions.(anonymous function) [as .js] (/vagrant/lingo-client-react/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@0.15.1 dev: `node --harmony bin/webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter-kit@0.15.1 dev script 'node --harmony bin/webpack-dev-server'.
npm ERR! This is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony bin/webpack-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/lingo-client-react/npm-debug.log

npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@0.15.1 start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter-kit@0.15.1 start script 'npm run dev'.
npm ERR! This is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/lingo-client-react/npm-debug.log
```

---

##### This is the `/vagrant/lingo-client-react/npm-debug.log`
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart react-redux-starter-kit@0.15.1
6 info start react-redux-starter-kit@0.15.1
7 verbose unsafe-perm in lifecycle true
8 info react-redux-starter-kit@0.15.1 Failed to exec start script
9 verbose stack Error: react-redux-starter-kit@0.15.1 start: `npm run dev`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-redux-starter-kit@0.15.1
11 verbose cwd /vagrant/lingo-client-react
12 error Linux 3.13.0-44-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
14 error node v4.1.1
15 error npm  v2.14.4
16 error code ELIFECYCLE
17 error react-redux-starter-kit@0.15.1 start: `npm run dev`
17 error Exit status 1
18 error Failed at the react-redux-starter-kit@0.15.1 start script 'npm run dev'.
18 error This is most likely a problem with the react-redux-starter-kit package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run dev
18 error You can get their info via:
18 error     npm owner ls react-redux-starter-kit
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by davezuko** [comment]
I really can't find much on this besides attempting to reinstall your global and local node_modules.

http://stackoverflow.com/questions/32566022/getting-an-error-related-to-babel-with-reactjs
https://github.com/gaearon/react-hot-boilerplate/issues/11

Have you tried that yet?

**Comment by jendiamond** [comment]
Thanks I'll try that an let you know.
