### ISSUE TITLE
npm start fails on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by davunderscorei** [davezuko/react-redux-starter-kit#1014]
Hey, trying to get set up on BoUoW; get the following log on failure:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-starter-kit@3.0.0-alpha.2~prestart: react-redux-starter-kit@3.0.0-alpha.2
6 silly lifecycle react-redux-starter-kit@3.0.0-alpha.2~prestart: no script for prestart, continuing
7 info lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: react-redux-starter-kit@3.0.0-alpha.2
8 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/<path>/node_modules/.bin:/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: CWD: /home/<path>
11 silly lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: Args: [ '-c', 'better-npm-run start' ]
12 silly lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: Returned: code: 1  signal: null
13 info lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: Failed to exec start script
14 verbose stack Error: react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-redux-starter-kit@3.0.0-alpha.2
16 verbose cwd /home/<path>
17 error Linux 3.4.0+
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.6.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
22 error Exit status 1
23 error Failed at the react-redux-starter-kit@3.0.0-alpha.2 start script 'better-npm-run start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     better-npm-run start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by davidlashlee** [comment]
I got this exact issue when working on a ubuntu vps. Will update if I figure anything out.

**Comment by climboid** [comment]
Any updates on how to solve this? Getting the error on windows 7

**Comment by davezuko** [comment]
Did this ever get resolved? I've been at a distance from this project for a while due to a severe lack of free time, but if it's still an issue I will take a look now that I'm back. Please just ping the issue again and we can reopen it. Thanks!

**Comment by Hacalox** [comment]
I have the exact same problem! @davezuko , if you get some free time take a look at it please!
Thank you!
