### ISSUE TITLE
error at first attempt to launch

### ISSUE THREAD

**Issue by mjabraham47** [davezuko/react-redux-starter-kit#1025]
```
Executing script: start

to be executed: node bin/server
  app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "development". +2ms
  app:config Found overrides, applying to default configuration. +2ms
  app:webpack:config Creating configuration. +520ms
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +1ms
module.js:440
    throw err;
    ^

Error: Cannot find module './utils'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/BeardedMac/projects/cv-react-redux/server/main.js:6:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/BeardedMac/projects/cv-react-redux/bin/server.js:2:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
```

**Comment by menthos984** [comment]
so what happened? did you fixed it? if yes, how?
