### ISSUE TITLE
Fail to run npm start: Server is now running at http://localhost:${port}

### ISSUE THREAD

**Issue by yinglinchen-minted** [davezuko/react-redux-starter-kit#1043]
Hi, 
I got this error after I try to run npm start. I tried to 'killall node' to kill node server, but still getting the error. Anyone has idea? 
```
Executing script: start

to be executed: node bin/server 
/Users/<myUserName>/src/todo/bin/server.js:7
debug(`Server is now running at http://localhost:${port}.`)
      ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by davezuko** [comment]
What Node version are you on? It appears to not support template strings.

**Comment by yinglinchen-minted** [comment]
I am using v0.12.4.

**Comment by davezuko** [comment]
Ah, ok, that explains it. As per the requirements specified in the README, you should be on at least Node `^4.5.0`: https://github.com/davezuko/react-redux-starter-kit#requirements. Sorry for the trouble.
