### ISSUE TITLE
Dev server does not start with default config

### ISSUE THREAD

**Issue by artemkaint** [davezuko/react-redux-starter-kit#111]
<pre><code>
// npm run compile

> react-redux-starter-kit@0.14.0 compile /tmp/11112/react-redux-starter-kit
> webpack

Hash: 152cd4dd18d2703f35b188eddc1f4f5c2151c2fa
Version: webpack 1.12.2
Child client:
    Hash: 152cd4dd18d2703f35b1
    Version: webpack 1.12.2
    Time: 9407ms
                                 Asset       Size  Chunks             Chunk Names
        vendor.152cd4dd18d2703f35b1.js    1.15 MB       0  [emitted]  vendor
           app.152cd4dd18d2703f35b1.js     347 kB       1  [emitted]  app
    vendor.152cd4dd18d2703f35b1.js.map    1.39 MB       0  [emitted]  vendor
       app.152cd4dd18d2703f35b1.js.map     419 kB       1  [emitted]  app
                            index.html  484 bytes          [emitted]  
       [0] multi vendor 112 bytes {0} [built]
       [0] multi app 52 bytes {1} [built]
        + 514 hidden modules
Child server:
    Hash: 88eddc1f4f5c2151c2fa
    Version: webpack 1.12.2
    Time: 9365ms
       Asset    Size  Chunks             Chunk Names
    index.js  204 kB       0  [emitted]  app
       [0] multi app 28 bytes {0} [built]
        + 189 hidden modules

// npm run server:dev

> react-redux-starter-kit@0.14.0 server:dev /tmp/11112/react-redux-starter-kit
> nodemon --harmony --watch server bin/server

30 Sep 12:42:04 - [nodemon] 1.7.1
30 Sep 12:42:04 - [nodemon] to restart at any time, enter `rs`
30 Sep 12:42:04 - [nodemon] watching: /tmp/11112/react-redux-starter-kit/server/**/*
30 Sep 12:42:04 - [nodemon] starting `node --harmony bin/server index.js`
[BABEL] Note: The code generator has deoptimised the styling of "/tmp/11112/react-redux-starter-kit/dist/server/index.js" as it exceeds the max of "100KB".
/tmp/11112/react-redux-starter-kit/node_modules/react-transform-hmr/lib/index.js:51
    throw new Error('locals[0] does not appear to be a `module` object with Ho
          ^
Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
    at proxyReactComponents (/tmp/11112/react-redux-starter-kit/node_modules/react-transform-hmr/lib/index.js:51:11)
    at Object.<anonymous> (/tmp/11112/react-redux-starter-kit/dist/server/index.js:1598:65)
    at Object.<anonymous> (/tmp/11112/react-redux-starter-kit/dist/server/index.js:1657:31)
    at __webpack_require__ (/tmp/11112/react-redux-starter-kit/dist/server/index.js:21:30)
    at Object.<anonymous> (/tmp/11112/react-redux-starter-kit/dist/server/index.js:894:27)
    at __webpack_require__ (/tmp/11112/react-redux-starter-kit/dist/server/index.js:21:30)
    at Object.<anonymous> (/tmp/11112/react-redux-starter-kit/dist/server/index.js:1516:16)
    at __webpack_require__ (/tmp/11112/react-redux-starter-kit/dist/server/index.js:21:30)
    at Object.<anonymous> (/tmp/11112/react-redux-starter-kit/dist/server/index.js:71:19)
    at __webpack_require__ (/tmp/11112/react-redux-starter-kit/dist/server/index.js:21:30)
30 Sep 12:42:07 - [nodemon] app crashed - waiting for file changes before starting...
</code></pre>

**Comment by artemkaint** [comment]
fix then i remove transform block in .babelrc

<pre><code>
 {
       "transform" : "react-transform-hmr",
       "imports" : ["react"],
       "locals" : ["module"]
 }, 
</code></pre>

**Comment by davezuko** [comment]
Hey thanks, yeah I'm aware of this and have a fix that will fix this a bit more cleanly. I'll update you when it gets implemented :).

**Comment by davezuko** [comment]
This has been fixed with https://github.com/davezuko/react-redux-starter-kit/releases/tag/v0.15.0
