### ISSUE TITLE
Clones library, runs locally, deploy fails 🔥

### ISSUE THREAD

**Issue by benstr** [davezuko/react-redux-starter-kit#1142]
Hey folks, was recommended this project by a co-worker. I like what I'm seeing!

Unfortunately as the current repo stands right now the deploy command fails. I suspect this is because of `node-sass` #791 . 

Steps to recreate: 
 - clone repo 👍 
 - `yarn install` 👍 
 - `yarn start` 👍 
 - `npm run compile` 👍 
 - `npm run deploy` 👎 🔥 

<details><summary>terminal output</summary><p>

```
➜ demo-react-starter git:(master) npm run deploy

> react-redux-starter-kit@3.0.0-alpha.2 deploy /Users/ben/code/benstr/demo-react-starter
> better-npm-run deploy

running better-npm-run in /Users/ben/code/benstr/demo-react-starter
Executing script: deploy

to be executed: npm run lint && npm run test && npm run clean && npm run compile

> react-redux-starter-kit@3.0.0-alpha.2 lint /Users/ben/code/benstr/demo-react-starter
> eslint bin build config server src tests


> react-redux-starter-kit@3.0.0-alpha.2 test /Users/ben/code/benstr/demo-react-starter
> better-npm-run test

running better-npm-run in /Users/ben/code/benstr/demo-react-starter
Executing script: test

to be executed: node ./node_modules/karma/bin/karma start config/karma.config
  app:config:project Creating default configuration. +0ms
  app:config:project Looking for environment overrides for NODE_ENV "test". +3ms
  app:config:project No environment overrides found, defaults will be used. +1ms
  app:config:webpack Creating configuration. +612ms
  app:config:webpack Applying ExtractTextPlugin to CSS loaders. +75ms
  app:config:karma Creating configuration. +1ms

START:
17 01 2017 16:23:34.014:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
17 01 2017 16:23:34.016:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
17 01 2017 16:23:34.029:INFO [launcher]: Starting browser PhantomJS
17 01 2017 16:23:35.019:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#iOVq-Sd1R_FSjcxSAAAA with id 80891435
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Use of reserved word 'import'
  at tests/test-bundler.js:4

Finished in 0.059 secs / 0 secs

SUMMARY:
✔ 0 tests completed

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/ben/.nvm/versions/node/v4.0.0/bin/node" "/Users/ben/.nvm/versions/node/v4.0.0/bin/npm" "run" "test"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@3.0.0-alpha.2 test: `better-npm-run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@3.0.0-alpha.2 test script 'better-npm-run test'.
npm ERR! This is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run test
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ben/code/benstr/demo-react-starter/npm-debug.log

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/ben/.nvm/versions/node/v4.0.0/bin/node" "/Users/ben/.nvm/versions/node/v4.0.0/bin/npm" "run" "deploy"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@3.0.0-alpha.2 deploy: `better-npm-run deploy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@3.0.0-alpha.2 deploy script 'better-npm-run deploy'.
npm ERR! This is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run deploy
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ben/code/benstr/demo-react-starter/npm-debug.log
```

</p></details>

<details><summary>npm-debug.log</summary><p>

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/ben/.nvm/versions/node/v4.0.0/bin/node',
1 verbose cli   '/Users/ben/.nvm/versions/node/v4.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info predeploy react-redux-starter-kit@3.0.0-alpha.2
6 info deploy react-redux-starter-kit@3.0.0-alpha.2
7 verbose unsafe-perm in lifecycle true
8 info react-redux-starter-kit@3.0.0-alpha.2 Failed to exec deploy script
9 verbose stack Error: react-redux-starter-kit@3.0.0-alpha.2 deploy: `better-npm-run deploy`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/ben/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/Users/ben/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-redux-starter-kit@3.0.0-alpha.2
11 verbose cwd /Users/ben/code/benstr/hackiot/fullSite/staticS3
12 error Darwin 16.3.0
13 error argv "/Users/ben/.nvm/versions/node/v4.0.0/bin/node" "/Users/ben/.nvm/versions/node/v4.0.0/bin/npm" "run" "deploy"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error react-redux-starter-kit@3.0.0-alpha.2 deploy: `better-npm-run deploy`
17 error Exit status 1
18 error Failed at the react-redux-starter-kit@3.0.0-alpha.2 deploy script 'better-npm-run deploy'.
18 error This is most likely a problem with the react-redux-starter-kit package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     better-npm-run deploy
18 error You can get their info via:
18 error     npm owner ls react-redux-starter-kit
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

</p></details>

**Comment by benstr** [comment]
My bad, was running Node v4. Changed to Node v6, ran `npm rebuild`, and now all is groovy!
