### ISSUE TITLE
error when run it

### ISSUE THREAD

**Issue by xinzhang** [davezuko/react-redux-starter-kit#1143]
just clone it, then after run npm install, run npm start, it seems all good.
when go to http://localhost:3000, error is thrown directly,

Error
   at MemoryFileSystem.readFileSync (C:\Projects\react\StarterKit\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:108:10)
   at MemoryFileSystem.(anonymous function) [as readFile] (C:\Projects\react\StarterKit\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:301:34)
   at C:\Projects\react\StarterKit\server\main.js:45:31
   at Layer.handle [as handle_request] (C:\Projects\react\StarterKit\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\Projects\react\StarterKit\node_modules\express\lib\router\index.js:312:13)
   at C:\Projects\react\StarterKit\node_modules\express\lib\router\index.js:280:7
   at param (C:\Projects\react\StarterKit\node_modules\express\lib\router\index.js:349:14)
   at param (C:\Projects\react\StarterKit\node_modules\express\lib\router\index.js:365:14)
   at Function.process_params (C:\Projects\react\StarterKit\node_modules\express\lib\router\index.js:410:3)
   at next (C:\Projects\react\StarterKit\node_modules\express\lib\router\index.js:271:10)

what this issue can be? am i missing anything to install globally?

**Comment by Xin-Zheng** [comment]
same problem!!

**Comment by bhj** [comment]
It seems related to webpack-dev-middleware 1.9.0; does `npm i webpack-dev-middleware@1.8.4` work?

**Comment by mikeodell77** [comment]
What output do you see on the command line when you run `npm start`?

**Comment by gxlfc** [comment]
npm rebuild node-sass
