### ISSUE TITLE
Couldn't find preset "env" error. Fresh build.

### ISSUE THREAD

**Issue by dougvk** [davezuko/react-redux-starter-kit#1156]
```
  app:bin:compile Webpack compiler encountered errors. +5ms
  app:bin:compile ./src/main.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/app"
    at /app/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/app/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/app/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/app/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/app/app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/app/app/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/app/app/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/app/app/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/app/app/node_modules/babel-loader/lib/index.js:41:20)
    at /app/app/node_modules/babel-loader/lib/fs-cache.js:159:18
    at ReadFileContext.callback (/app/app/node_modules/babel-loader/lib/fs-cache.js:30:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
 @ multi app +0ms
  app:bin:compile Compiler encountered an error. Error: Webpack compiler encountered errors
    at compiler.run (/app/app/bin/compile.js:25:23)
    at Compiler.<anonymous> (/app/app/node_modules/webpack/lib/Compiler.js:181:13)
    at /app/app/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/app/app/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/app/app/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/app/app/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/app/app/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/app/app/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/app/app/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/app/app/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/app/app/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/app/app/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.applyPluginsAsync (/app/app/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/app/app/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.applyPluginsAsync (/app/app/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/app/app/node_modules/webpack/lib/Compilation.js:525:7) +4ms
```

**Comment by J-F-Liu** [comment]
npm install babel-preset-env --save-dev

**Comment by kmg1434** [comment]
I am having this exact issue, even after running `npm install babel-preset-env --save-dev` as @J-F-Liu requested.

```
~/wdi/projects/react-redux-starter-kit (master)$ npm start

> react-redux-starter-kit@3.0.0-alpha.2 start /Users/Shrugs/wdi/projects/react-redux-starter-kit
> better-npm-run start

running better-npm-run in /Users/Shrugs/wdi/projects/react-redux-starter-kit
Executing script: start

to be executed: node bin/dev-server 
  app:config:project Creating default configuration. +0ms
  app:config:project Looking for environment overrides for NODE_ENV "development". +3ms
  app:config:project Found overrides, applying to default configuration. +1ms
  app:config:webpack Creating configuration. +901ms
  app:config:webpack Enabling plugins for live development (HMR, NoErrors). +2ms
  app:server Enabling webpack dev and HMR middleware +115ms
  app:bin:dev-server Server is now running at http://localhost:3000. +54ms
webpack built 34f37017358c17e13fcc in 1534ms
Hash: 34f37017358c17e13fcc
Version: webpack 1.14.0
Time: 1534ms
                             Asset     Size  Chunks       Chunk Names
       app.34f37017358c17e13fcc.js  82.9 kB       0       app
    vendor.34f37017358c17e13fcc.js   402 kB       1       vendor
   app.34f37017358c17e13fcc.js.map    92 kB       0       app
vendor.34f37017358c17e13fcc.js.map   481 kB       1       vendor

ERROR in ./src/main.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/Shrugs"
    at /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-loader/lib/index.js:46:20)
    at /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-loader/lib/fs-cache.js:79:18
    at ReadFileContext.callback (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-loader/lib/fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
 @ multi app
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  578 kB       0       
webpack: Failed to compile.
```

Any clues on what to try? Stackoverflow doesn't seem to have much.

**Comment by davezuko** [comment]
`babel-preset-env` was not present in this project at the time of it being reported. However, with https://github.com/davezuko/react-redux-starter-kit/releases/tag/v3.0.0 released, we now officially support it. Closing this as it should no longer be an issue.
