### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by hungkoala** [davezuko/react-redux-starter-kit#1174]
ERROR in ./src/layouts/CoreLayout/CoreLayout.js
Module build failed: Error: /Users/hung/project/myredux/src/layouts/CoreLayout/CoreLayout.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/modification.js:175:13)
    at PluginPass.VariableDeclarator (/Users/hung/project/ego-pulse/pulse/phoenix/babel/transform-react-display-name.js:37:27)
    at newFn (/Users/hung/project/myredux/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/hung/project/myredux/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/hung/project/myredux/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:115:19)
 @ ./src/layouts/CoreLayout/index.js 7:18-41

ERROR in ./src/routes/Home/components/HomeView.js
Module build failed: Error: /Users/hung/project/myredux/src/routes/Home/components/HomeView.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/modification.js:175:13)
    at PluginPass.VariableDeclarator (/Users/hung/project/ego-pulse/pulse/phoenix/babel/transform-react-display-name.js:37:27)
    at newFn (/Users/hung/project/myredux/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/hung/project/myredux/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/hung/project/myredux/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:115:19)
 @ ./src/routes/Home/index.js 7:16-48

ERROR in ./src/routes/Counter/components/Counter.js
Module build failed: Error: /Users/hung/project/myredux/src/routes/Counter/components/Counter.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/modification.js:175:13)
    at PluginPass.VariableDeclarator (/Users/hung/project/ego-pulse/pulse/phoenix/babel/transform-react-display-name.js:37:27)
    at newFn (/Users/hung/project/myredux/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (/Users/hung/project/myredux/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/hung/project/myredux/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (/Users/hung/project/myredux/node_modules/babel-traverse/lib/path/context.js:115:19)
 @ ./src/routes/Counter/containers/CounterContainer.js 11:15-47
Child html-webpack-plugin for "index.html":

**Comment by davezuko** [comment]
Closing since the compiler has been completely rewritten with https://github.com/davezuko/react-redux-starter-kit/releases/tag/v3.0.0.
