### ISSUE TITLE
Module Build Failed: Error: Couldn't find preset "env"

### ISSUE THREAD

**Issue by kmg1434** [davezuko/react-redux-starter-kit#1190]
Hello there, just trying to get started using React/Redux. Following the directions, `npm install` gave me a couple warnings:

```
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

> fsevents@1.1.1 install /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/fsevents
> node install

[fsevents] Success: "/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> execSync@1.0.2 install /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> phantomjs-prebuilt@2.1.14 install /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/phantomjs-prebuilt
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Found PhantomJS at /usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ...verifying
Writing location.js file
PhantomJS linked at /usr/local/lib/node_modules/phantomjs-prebuilt/lib/location

> node-sass@4.5.0 install /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/Shrugs/.npm/node-sass/4.5.0/darwin-x64-51_binding.node

> node-sass@4.5.0 postinstall /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/node-sass/vendor/darwin-x64-51/binding.node
Testing binary
Binary is fine
react-redux-starter-kit@3.0.0-alpha.2 /Users/Shrugs/wdi/projects/react-redux-starter-kit
```

I then tried `npm start` and I'm getting this errror:

```
> react-redux-starter-kit@3.0.0-alpha.2 start /Users/Shrugs/wdi/projects/react-redux-starter-kit
> better-npm-run start

running better-npm-run in /Users/Shrugs/wdi/projects/react-redux-starter-kit
Executing script: start

to be executed: node bin/dev-server 
  app:config:project Creating default configuration. +0ms
  app:config:project Looking for environment overrides for NODE_ENV "development". +3ms
  app:config:project Found overrides, applying to default configuration. +1ms
  app:config:webpack Creating configuration. +572ms
  app:config:webpack Enabling plugins for live development (HMR, NoErrors). +1ms
  app:server Enabling webpack dev and HMR middleware +81ms
  app:bin:dev-server Server is now running at http://localhost:3000. +34ms
webpack built 53873d82adc49e0e6368 in 1159ms
Hash: 53873d82adc49e0e6368
Version: webpack 1.14.0
Time: 1159ms
                             Asset     Size  Chunks       Chunk Names
       app.53873d82adc49e0e6368.js  82.9 kB       0       app
    vendor.53873d82adc49e0e6368.js   390 kB       1       vendor
   app.53873d82adc49e0e6368.js.map  91.6 kB       0       app
vendor.53873d82adc49e0e6368.js.map   464 kB       1       vendor

ERROR in ./src/main.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/Shrugs"
    at /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-loader/lib/index.js:46:20)
    at /Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-loader/lib/fs-cache.js:79:18
    at ReadFileContext.callback (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/babel-loader/lib/fs-cache.js:15:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:335:13)
 @ multi app
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  578 kB       0       
webpack: Failed to compile.
```

So naturally I tried `npm install babel-preset-env` which installed fine but the same error occurs. I also tried `touch .env` and `touch server/.env` just for kicks and that didn't help either. Any tips will be greatly appreciated, thanks!

**Comment by piu130** [comment]
Did you modify some files or is this a fresh copy of the project?

**Comment by kmg1434** [comment]
@piu130 I did not modify any files, this is a fresh copy of the project.

**Comment by kmg1434** [comment]
So I ran `npm install -g npm` a few times and it seems to have changed my error. Now when running `npm start` I get the following error:

```
> react-redux-starter-kit@3.0.0-alpha.2 start /Users/Shrugs/wdi/projects/react-redux-starter-kit
> better-npm-run start

running better-npm-run in /Users/Shrugs/wdi/projects/react-redux-starter-kit
Executing script: start

to be executed: node bin/dev-server 
  app:config:project Creating default configuration. +0ms
  app:config:project Looking for environment overrides for NODE_ENV "development". +3ms
  app:config:project Found overrides, applying to default configuration. +1ms
  app:config:webpack Creating configuration. +988ms
  app:config:webpack Enabling plugins for live development (HMR, NoErrors). +2ms
  app:server Enabling webpack dev and HMR middleware +113ms
  app:bin:dev-server Server is now running at http://localhost:3000. +51ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at EventEmitter.listen (/Users/Shrugs/wdi/projects/react-redux-starter-kit/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/Shrugs/wdi/projects/react-redux-starter-kit/bin/dev-server.js:5:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter-kit@3.0.0-alpha.2 start script 'better-npm-run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Shrugs/.npm/_logs/2017-03-15T22_54_11_305Z-debug.log
```

I can't seem to find much in the github issues on this specific topic. 

I treid with a few versions of npm and node using nvm: 
```
~/wdi/projects/react-redux-starter-kit (master)$ npm -v
4.4.1
~/wdi/projects/react-redux-starter-kit (master)$ node -v
v4.7.3
```
and
```
~/wdi/projects/react-redux-starter-kit (master)$ npm -v
3.10.10
~/wdi/projects/react-redux-starter-kit (master)$ node -v
v7.2.1
```

**Comment by przeor** [comment]
@kmg1434 it looks, like the ports 3000 are already in use. When I try to run two different projects at the same time on the same 3000 ports, then I get similar error:
<img width="1279" alt="screen shot 2017-03-16 at 00 38 28" src="https://cloud.githubusercontent.com/assets/5995/23975442/029f06fc-09e1-11e7-8633-3b1875865866.png">

**Comment by kmg1434** [comment]
@przeor Ah, of course. What a silly mistake. Well I've shut down my other local server and I'm back to square one again, same error as before. 

I've tried `npm install babel-preset-env`, I've tried adding `"babel-preset-env": "^1.2.2",` to my `package.json` file, and re-running `npm install` but this has not changed my error.

**Comment by jarvelov** [comment]
Just wanted to let others know how I  got it running:

The fix was to create a `.babelrc` with the following config:

```shell {
  "plugins": ["transform-runtime"],
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ]
}
```

**Comment by kmg1434** [comment]
Had I kept scrolling on the readme I would have noticed to move the git head to an earlier commit that included a .babelrc file with most of what jarvelov posted. This worked, thanks for the help!
