### ISSUE TITLE
Your push updates today

### ISSUE THREAD

**Issue by richyrb00** [davezuko/react-redux-starter-kit#1244]
i seem to be getting errors in setup with the new updates.

git clone
yarn

yarn is on 0.24.5

yarn start errors with:

yarn start v0.24.5
$ cross-env NODE_ENV=development node build/scripts/start 
/test-app/build/lib/logger.js:4
exports.log = (...messages) => console.log(...messages)
               ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/test-app/build/scripts/start.js:1:78)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
error Command failed with exit code 1.

**Comment by davezuko** [comment]
@richyrb00 I figured, I inadvertently bumped the required node version. I'll push a quick fix for you.

**Comment by davezuko** [comment]
Tracking in https://github.com/davezuko/react-redux-starter-kit/pull/1245.
