### ISSUE TITLE
Cloned repo today and did yarn install, then yarn start and ran into error

### ISSUE THREAD

**Issue by yenly** [davezuko/react-redux-starter-kit#1290]
```yarn start
yarn start v0.24.6
$ cross-env NODE_ENV=development node build/scripts/start 
ℹ Starting server...
ℹ Enabling webpack development and HMR middleware
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1307:14)
    at listenInCluster (net.js:1355:12)
    at Server.listen (net.js:1455:7)
    at Function.listen (/Users/yenly/playgd/slick_slider/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/yenly/playgd/slick_slider/build/scripts/start.js:4:30)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 1.```

**Comment by Dr1Ku** [comment]
Hi, the error is verbose enough -- you're running another service on port `3000`, where the Webpack development server should run at.

Try running `netstat -anp | grep 3000` in a term to check for any other programs/services occupying the port.

**Comment by yenly** [comment]
Hi Dr1Ku, Thank you for the quick response! I tried it again and it worked.
