### ISSUE TITLE
when save the code ,auto compile error ( TypeError: Cannot read property 'startsWith' of undefined )

### ISSUE THREAD

**Issue by zaoansijia** [davezuko/react-redux-starter-kit#1316]
when I save the code ,compile error. error :

    TypeError: Cannot read property 'startsWith' of undefined
    at Storage.purge (D:\anan\reactStartA\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:145:20)
    at Storage.purge (D:\anan\reactStartA\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:150:18)
    at CachedInputFileSystem.purge (D:\anan\reactStartA\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:259:23)
    at EventEmitter.watcher.once (D:\anan\reactStartA\node_modules\webpack\lib\node\NodeWatchFileSystem.js:42:26)
    at EventEmitter.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter._onTimeout (D:\anan\reactStartA\node_modules\watchpack\lib\watchpack.js:142:7)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by zaoansijia** [comment]
I know the reason ,beacasue this project package 'enhanced-resolve' is old ,delete enhanced-resolve package and install it again;
npm install enhanced-resolve@lastest
