### ISSUE TITLE
verbose stack Error: react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`

### ISSUE THREAD

**Issue by comeriven** [davezuko/react-redux-starter-kit#1334]
hello, 
When I started the project with "npm start", an error occurred.  
I read the other issue, I use the administrator account to install all the modules.  
But it does not work.    
thanks for your time!

# node version v4.4.7  

# npm version 3.7.2

# img
![qq 20171017140416](https://user-images.githubusercontent.com/19868056/31649093-cddb6318-b343-11e7-8842-cd31789717e9.png)

# npm-debug.log  
  
    0 info it worked if it ends with ok
    1 verbose cli [ 'D:\\nodejs\\node.exe',
    1 verbose cli   'D:\\nodejs\\npm-global\\node_modules\\npm\\bin\\npm-cli.js',
    1 verbose cli   'start' ]
    2 info using npm@3.7.2
    3 info using node@v4.4.7
    4 verbose run-script [ 'prestart', 'start', 'poststart' ]
    5 info lifecycle react-redux-starter-kit@3.0.0-alpha.2~prestart: react-redux-starter-kit@3.0.0-alpha.2
    6 silly lifecycle react-redux-starter-kit@3.0.0-alpha.2~prestart: no script for prestart, continuing
    7 info lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: react-redux-starter-kit@3.0.0-alpha.2
    8 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: unsafe-perm in lifecycle true
    9 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: PATH: D:\nvm\v4.4.7\npm-global\node_modules\npm\bin\node-gyp-bin;D:\workspace\MFT\node_modules\.bin;D:\nodejs;D:\cmder\bin;D:\cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\cmder\vendor\git-for-windows\usr\bin;D:\cmder\vendor\conemu-maximus5;D:\cmder\vendor\conemu-maximus5\ConEmu;D:\Python27\;D:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\TortoiseSVN\bin;D:\Git\cmd;D:\workspace\nginx-1.8.1;%CMDER_HOME%;C:\Users\shwh\.nvm;%NVM_HOME%;%NVM_SYMLINK%;;D:\MicrosoftVSCode\bin;D:\nvm;D:\nodejs;D:\cmder
    10 verbose lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: CWD: D:\workspace\MFT
    11 silly lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: Args: [ '/d /s /c', 'better-npm-run start' ]
    12 silly lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: Returned: code: 1  signal: null
    13 info lifecycle react-redux-starter-kit@3.0.0-alpha.2~start: Failed to exec start script
    14 verbose stack Error: react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
    14 verbose stack Exit status 1
    14 verbose stack     at EventEmitter.<anonymous> (D:\nvm\v4.4.7\npm-global\node_modules\npm\lib\utils\lifecycle.js:239:16)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at EventEmitter.emit (events.js:172:7)
    14 verbose stack     at ChildProcess.<anonymous> (D:\nvm\v4.4.7\npm-global\node_modules\npm\lib\utils\spawn.js:24:14)
    14 verbose stack     at emitTwo (events.js:87:13)
    14 verbose stack     at ChildProcess.emit (events.js:172:7)
    14 verbose stack     at maybeClose (internal/child_process.js:827:16)
    14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    15 verbose pkgid react-redux-starter-kit@3.0.0-alpha.2
    16 verbose cwd D:\workspace\MFT
    17 error Windows_NT 10.0.10240
    18 error argv "D:\\nodejs\\node.exe" "D:\\nodejs\\npm-global\\node_modules\\npm\\bin\\npm-cli.js" "start"
    19 error node v4.4.7
    20 error npm  v3.7.2
    21 error code ELIFECYCLE
    22 error react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
    22 error Exit status 1
    23 error Failed at the react-redux-starter-kit@3.0.0-alpha.2 start script 'better-npm-run start'.
    23 error Make sure you have the latest version of node.js and npm installed.
    23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
    23 error not with npm itself.
    23 error Tell the author that this fails on your system:
    23 error     better-npm-run start
    23 error You can get information on how to open an issue for this project with:
    23 error     npm bugs react-redux-starter-kit
    23 error Or if that isn't available, you can get their info via:
    23 error     npm owner ls react-redux-starter-kit
    23 error There is likely additional logging output above.
    24 verbose exit [ 1, true ]

**Comment by comeriven** [comment]
Restoring the previous version can work
