### ISSUE TITLE
Can't run `npm start`

### ISSUE THREAD

**Issue by silent1mezzo** [davezuko/react-redux-starter-kit#143]
When I follow the instructions in the `Getting Started` section and run `npm start` I receive the following error log.

I know it has something to do with the backticks in the console.log but I'm fairly new to JS and I'm not sure where I went wrong.

```
$ npm start

> react-redux-starter-kit@0.16.0 start /Users/.../ReduxStarterApp
> npm run dev


> react-redux-starter-kit@0.16.0 dev /Users/.../ReduxStarterApp
> node --harmony bin/webpack-dev-server

/Users/.../ReduxStarterApp/bin/webpack-dev-server.js:9
  console.log(`Webpack dev server running at ${host}: ${port}`);
              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@0.16.0 dev: `node --harmony bin/webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@0.16.0 dev script 'node --harmony bin/webpack-dev-server'.
npm ERR! This is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony bin/webpack-dev-server
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../ReduxStarterApp/npm-debug.log

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@0.16.0 start: `npm run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@0.16.0 start script 'npm run dev'.
npm ERR! This is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/.../ReduxStarterApp/npm-debug.log

```

**Comment by davezuko** [comment]
Hey, it's because that file (`bin/webpack-dev-server`) is not being transpiled by Babel and your Node version does not natively support string templates (the backticks). My recommendation would be to update your Node version (it's not at a stable `^4.0.0` release), but if you don't want to do that you could just change that `console.log` to use a regular string literal:

`console.log('Webpack dev server running at ' + host + ':' + port);`

Hopefully that solves your problem.

**Comment by silent1mezzo** [comment]
+1 thanks for the help!
