### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by realadeel** [davezuko/react-redux-starter-kit#350]
After npm install, npm start causes an error. Similar to #325 but I'm on the latest node and npm.

I'm seeing this error on the latest node and npm.
npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-redux-starter-kit@0.18.0~prestart: react-redux-starter-kit@0.18.0
6 silly lifecycle react-redux-starter-kit@0.18.0~prestart: no script for prestart, continuing
7 info lifecycle react-redux-starter-kit@0.18.0~start: react-redux-starter-kit@0.18.0
8 verbose lifecycle react-redux-starter-kit@0.18.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter-kit@0.18.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/adeel/Projects/react-redux-starter-kit/node_modules/.bin:/Users/adeel/.rvm/gems/ruby-2.2.3/bin:/Users/adeel/.rvm/gems/ruby-2.2.3@global/bin:/Users/adeel/.rvm/rubies/ruby-2.2.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/heroku/bin:/usr/local/heroku/bin:/opt/local/bin:/opt/local/sbin:/Users/adeel/.rvm/gems/ruby-2.2.2@warsaw/bin:/Users/adeel/.rvm/gems/ruby-2.2.2@global/bin:/Users/adeel/.rvm/rubies/ruby-2.2.2/bin:/Users/adeel/.rvm/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/sbin:/usr/sbin:/Users/adeel/bin:/Users/adeel/.rvm/bin:/Development/android-sdk-macosx/platform-tools:/Development/android-sdk-macosx/tools
10 verbose lifecycle react-redux-starter-kit@0.18.0~start: CWD: /Users/adeel/Projects/react-redux-starter-kit
11 silly lifecycle react-redux-starter-kit@0.18.0~start: Args: [ '-c', 'npm run dev' ]
12 silly lifecycle react-redux-starter-kit@0.18.0~start: Returned: code: 1 signal: null
13 info lifecycle react-redux-starter-kit@0.18.0~start: Failed to exec start script
14 verbose stack Error: react-redux-starter-kit@0.18.0 start: npm run dev
14 verbose stack Exit status 1
14 verbose stack at EventEmitter. (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack at emitTwo (events.js:87:13)
14 verbose stack at EventEmitter.emit (events.js:172:7)
14 verbose stack at ChildProcess. (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack at emitTwo (events.js:87:13)
14 verbose stack at ChildProcess.emit (events.js:172:7)
14 verbose stack at maybeClose (internal/child_process.js:818:16)
14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-redux-starter-kit@0.18.0
16 verbose cwd /Users/adeel/Projects/react-redux-starter-kit
17 error Darwin 14.5.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.3.0
20 error npm v3.5.2
21 error code ELIFECYCLE
22 error react-redux-starter-kit@0.18.0 start: npm run dev
22 error Exit status 1
23 error Failed at the react-redux-starter-kit@0.18.0 start script 'npm run dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error npm run dev
23 error You can get information on how to open an issue for this project with:
23 error npm bugs react-redux-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error npm owner ls react-redux-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by davezuko** [comment]
Just out of curiosity, could you try cloning the latest version of master and see if that works?

**Comment by realadeel** [comment]
I actually did that first (cloned master) and got the same issue.

**Comment by davezuko** [comment]
Hm, just installed matching node/npm versions as you, reinstalled, and couldn't reproduce. I'll be a bit busy the next few days due to the holidays, but will try to dig deeper into this when I get some time. Sorry for the troubles.

**Comment by realadeel** [comment]
More info, on closer inspection of npm install, it did not complete completely successfully:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! path /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/request-254baf4d/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/request-254baf4d/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/request-254baf4d/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by realadeel** [comment]
Thanks for checking on this during the holidays - happy holidays!

**Comment by realadeel** [comment]
Just some more info, looks like it is looking for node_modules/.staging/xxxx/package.json
I verified it exists through most of the install but the .staging directory disappears at some point.
```
87143 silly gentlyRm /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/caniuse-db-9e9abda0/node_modules is being purged
87144 verbose gentlyRm don't care about contents; nuking /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/caniuse-db-9e9abda0/node_modules
87145 silly gentlyRm /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/es5-ext-6ef48a5a/node_modules is being purged
87146 verbose gentlyRm don't care about contents; nuking /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/es5-ext-6ef48a5a/node_modules
87147 silly gentlyRm /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/core-js-dae5bcec/node_modules is being purged
87148 verbose gentlyRm don't care about contents; nuking /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/core-js-dae5bcec/node_modules
87149 silly gentlyRm /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/fsevents-4c409fff/node_modules is being purged
87150 verbose gentlyRm don't care about contents; nuking /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/fsevents-4c409fff/node_modules
87151 silly vacuum-fs purging /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/fsevents-4c409fff/node_modules
87152 silly vacuum-fs quitting because other entries in /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/fsevents-4c409fff
87153 verbose unlock done using /Users/adeel/.npm/_locks/staging-853a4b9831e1b254.lock for /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging
87154 silly rollbackFailedOptional Starting
87155 silly rollbackFailedOptional Finishing
87156 silly runTopLevelLifecycles Starting
87157 silly runTopLevelLifecycles Finishing
87158 silly install printInstalled
87159 verbose stack Error: ENOENT: no such file or directory, open '/Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/request-254baf4d/package.json'
87159 verbose stack     at Error (native)
87160 verbose cwd /Users/adeel/Projects/react-redux-starter-kit
87161 error Darwin 14.5.0
87162 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
87163 error node v5.3.0
87164 error npm  v3.5.2
87165 error path /Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/request-254baf4d/package.json
87166 error code ENOENT
87167 error errno -2
87168 error syscall open
87169 error enoent ENOENT: no such file or directory, open '/Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/request-254baf4d/package.json'
87170 error enoent ENOENT: no such file or directory, open '/Users/adeel/Projects/react-redux-starter-kit/node_modules/.staging/request-254baf4d/package.json'
87170 error enoent This is most likely not a problem with npm itself
87170 error enoent and is related to npm not being able to find a file.
87171 verbose exit [ -2, true ]
```

**Comment by davezuko** [comment]
I'm far from an npm expert, but what if you clear your node_modules, run `npm cache clean`, and then retry? Digging through npm issues right now, since this doesn't appear to be related to this project.

**Comment by realadeel** [comment]
npm cache clean before installing worked. Closing! Thank you!!
Hope this helps someone else. This issue was indeed unrelated to this project.

**Comment by davezuko** [comment]
:+1: :tada:  :santa:
