### ISSUE TITLE
You should fix eslint version in package.json 

### ISSUE THREAD

**Issue by nodkz** [davezuko/react-redux-starter-kit#36]
Can not start todo-example today. 
Get error when run `npm run dev:debug`:
```
ERROR in ./src/reducers/todos/index.js
Module build failed: TypeError: Cannot read property 'loc' of undefined
    at getNodeIndent (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint/lib/rules/indent.js:112:49)
    at EventEmitter.Program (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint/lib/rules/indent.js:547:45)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint/lib/eslint.js:815:25)
    at Controller.__execute (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint/lib/eslint.js:808:24)
    at processText (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint/lib/cli-engine.js:199:27)
    at CLIEngine.executeOnText (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint/lib/cli-engine.js:430:26)
    at lint (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint-loader/index.js:26:20)
    at Object.module.exports (/Users/nod/www/_nodejs/react-redux-todo/node_modules/eslint-loader/index.js:120:7)
 @ ./src/reducers/index.js 11:13-31
```

Problem in eslint@1.3.1. With 1.2.1 works perfectly:
```
npm uninstall eslint
npm install eslint@1.2.1
npm run dev:debug 
```

**Comment by davezuko** [comment]
Posted a bug report on eslint: https://github.com/eslint/eslint/issues/3596

It has to do with the first line of a file being blank. I'll remove the blank line for now, but should be able to maintain eslint 1.3.1 unless it causes other problems.

**Comment by davezuko** [comment]
https://github.com/davezuko/react-redux-starter-kit/commit/e99abf324d53b0fb0fea82d4c8e449c667c9d8c7 has fixed the issue for me. Hopefully eslint submits a patch soon, but this should suffice for the meantime.
