### ISSUE TITLE
Karma/PhantomJS Errors in CI environment when running npm test

### ISSUE THREAD

**Issue by fmr** [davezuko/react-redux-starter-kit#392]
Hi all,

I'm wondering if anyone's had a similar problem. Running the starter kit locally including tests seem to work fine, but as soon as it's run in our CI environment (Codeship), `npm test` fails. Prior to upgrading to the latest version (1.0.0), I was using v0.17.0 prior to this, which worked without any problems with Codeship.

I'm not sure if it's a webpack, babel, karma or phantomjs issue. I'm hoping someone can point me in the right direction.

The output of interest is:

```
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating '(0,_typeof3.default)(window)')
  at /home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/tests/framework.spec.js:527
```

Here's some sample output (with some lines removed for brevity):

```
rof@railsonfire_ec3a6ca0-94b8-0133-92f4-3671cbe1f766_a339f4178fa2:~/clone$ NODE_ENV=development npm test

> react-redux-starter-kit@1.0.0 test /home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit
> node -r dotenv/config ./node_modules/karma/bin/karma start bin/karma.js

  app:config Create configuration. +0ms
  app:config Apply environment overrides for NODE_ENV "development". +3ms
  app:webpack:_base Create configuration. +601ms
  app:webpack:_base Apply ExtractTextPlugin to CSS loaders. +10ms
  app:webpack:development Create configuration. +6ms
  app:webpack:development Enable devtool: "source-maps". +0ms
  app:karma Create configuration. +1ms
Hash: 007c5756153903691fdd
Version: webpack 1.12.9
Time: 20577ms
                                                                Asset           Size  Chunks             Chunk Names
                                         tests/views/HomeView.spec.js        10.5 MB       0  [emitted]  tests/views/HomeView.spec.js
                                     tests/layouts/CoreLayout.spec.js        7.54 MB       1  [emitted]  tests/layouts/CoreLayout.spec.js
                                              tests/framework.spec.js        1.55 MB       2  [emitted]  tests/framework.spec.js
tests/layouts/CoreLayout.spec.js.12d263862b958551ad1c8a65f1c79207.css        22.9 kB       1  [emitted]  tests/layouts/CoreLayout.spec.js
    tests/views/HomeView.spec.js.378e817da4b885132ac0d0a9142682dc.css      734 bytes       0  [emitted]  tests/views/HomeView.spec.js
                                                          favicon.ico  NaN undefined          [emitted]
                                                           index.html      837 bytes          [emitted]


<------------ snip ------------>

ERROR in ./~/redux-actions/lib/index.js
Module build failed: ReferenceError: [BABEL] /home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/redux-actions/lib/index.js: Unknown option: /home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/redux-actions/.babelrc.stage
    at Logger.error (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.addConfig (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Instrumenter.instrumentSync (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/isparta/lib/instrumenter.js:64:55)
    at Object.module.exports (/home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/node_modules/isparta-loader/index.js:18:25)
 @ ./src/redux/modules/counter.js 12:505-529
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 9.59 kB [rendered]
        [0] ./~/css-loader?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader!./src/views/HomeView.scss 710 bytes {0} [built]
        [1] ./~/css-loader/lib/css-base.js 8.88 kB {0} [built]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 28.5 kB [rendered]
        [0] ./~/css-loader?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader!./src/styles/core.scss 19.6 kB {0} [built]
        [1] ./~/css-loader/lib/css-base.js 8.88 kB {0} [built]
04 01 2016 03:28:11.697:INFO [karma]: Karma v0.13.16 server started at http://localhost:9876/
04 01 2016 03:28:11.708:INFO [launcher]: Starting browser PhantomJS
04 01 2016 03:28:12.179:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket MLSsOKrB7dNAdpkDAAAA with id 76382514
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating '(0,_typeof3.default)(window)')
  at /home/rof/src/bitbucket.org/<redacted>/react-redux-starter-kit/tests/framework.spec.js:527

PhantomJS 1.9.8 (Linux 0.0.0): Executed 0 of 0 ERROR (0.142 secs / 0 secs)
```

**Comment by davezuko** [comment]
What version of node/nom are you using with CI?

If memory serves correctly, `TypeError: 'undefined' is not a function (evaluating '(0,_typeof3.default)(window)')` has been fixed with a recent Babel release, but it could also be tied to the lack of the `add-module-exports` plugin. If you're not using that plugin, then you'll need to change require statements to the following pattern: `require('...').default`, but this _should_ be working properly in the starter kit.

Does clearing your node_modules cache in CI fix have any effect?

**Comment by dmcd** [comment]
I'm also seeing the exact same issue when running tests with Drone using the node:5-onbuild docker image. I haven't changed the node versions from what were configured in the starter kit. Clearingv node_modules doesn't seem to help.

**Comment by fmr** [comment]
Hi @davezuko, thanks for the response!

I'm using node 5.0.0 and npm 3.3.6. I have also tried with node 4.2, with the same results. In my CI set-up, I do an `rm -rf node_modules` prior to doing an `npm install`. 

I literally pushed `react-redux-starter-kit`'s master branch on there to make sure it's not something I misconfigured in my project. As such, all the dependencies, including `babel-plugin-add-module-exports` are installed.

Updated output from CI:

```
05 01 2016 01:18:23.223:INFO [karma]: Karma v0.13.18 server started at http://localhost:9876/
05 01 2016 01:18:23.236:INFO [launcher]: Starting browser PhantomJS
05 01 2016 01:18:23.729:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket IYovDExB8qQzjdnbAAAA with id 29991196
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
TypeError: 'undefined' is not a function (evaluating '(0,s["default"])(window)')
at /home/rof/src/bitbucket.org/mobileembrace/quan/tests/framework.spec.js:2

PhantomJS 1.9.8 (Linux 0.0.0): Executed 0 of 0 ERROR (0.136 secs / 0 secs)


npm ERR! Linux 3.13.0-58-generic
npm ERR! argv "/home/rof/.nvm/versions/node/v5.0.0/bin/node" "/home/rof/.nvm/versions/node/v5.0.0/bin/npm" "run" "test"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@1.0.0 test: `node -r dotenv/config ./node_modules/karma/bin/karma start bin/karma.js`
npm ERR! Exit status 1
```

**Comment by ecasilla** [comment]
+1

**Comment by dmcd** [comment]
I've just tried again with react-redux-starter-kit master branch (excluding my changes) and its building ok with v5.3.0 and npm v3.3.12. 

The problem for me was that I hadn't pulled down the latest change to exclude node_modules from the coverage report in build/karma.conf.js

exclude: /node_modules/

**Comment by fmr** [comment]
Hi @dmcd, thanks for the tip! I have just updated to the latest version on the master branch and triggered another build. It seems to build now :) The issue I'm having seems to have been fixed in one of the commits in the past day.

I'll close this issue now as it looks like it's fixed in the latest version.

Cheers everyone! Thanks @davezuko for merging all those PRs!

**Comment by davezuko** [comment]
@fmr really glad you figured this out, I read through the emails last night and was really at a loss... pleasantly surprised when I woke up, though :)
