### ISSUE TITLE
Error in multi app

### ISSUE THREAD

**Issue by WenXuanYuan** [davezuko/react-redux-starter-kit#400]
ERROR in multi app
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit
 @ multi app

I used npm install installed all components, when I run npm start, the error occured, what should i do ?

**Comment by davezuko** [comment]
Hey, could you please try checking out the branch from this PR: https://github.com/davezuko/react-redux-starter-kit/pull/401 (branch is `hotfix/koa`), reinstall node_modules and let me know if it works?

**Comment by WenXuanYuan** [comment]
Let me have a try .

**Comment by WenXuanYuan** [comment]
Some new error occured.
ERROR in ./src/containers/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/redbox-react/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/containers
 @ ./src/containers/Root.js 29:13-160

ERROR in ./src/containers/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/react-transform-catch-errors/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/containers
 @ ./src/containers/Root.js 33:14-177

ERROR in ./src/containers/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/react-transform-hmr/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/containers
 @ ./src/containers/Root.js 41:14-168

ERROR in ./src/views/AboutView.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/redbox-react/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views
 @ ./src/views/AboutView.js 28:13-160

ERROR in ./src/views/AboutView.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/react-transform-catch-errors/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views
 @ ./src/views/AboutView.js 32:14-177

ERROR in ./src/views/AboutView.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/react-transform-hmr/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views
 @ ./src/views/AboutView.js 40:14-168

ERROR in ./src/views/HomeView.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/redbox-react/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views
 @ ./src/views/HomeView.js 30:13-160

ERROR in ./src/views/HomeView.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/react-transform-catch-errors/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views
 @ ./src/views/HomeView.js 34:14-177

ERROR in ./src/views/HomeView.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/react-transform-hmr/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views
 @ ./src/views/HomeView.js 42:14-168

What should I do?

**Comment by davezuko** [comment]
npm2, right? I've been targeting the starter kit @ npm3, and this issue is due to the differences between the directory structures generated by `npm install` w/ npm2 and npm3. As a workaround, you could install and save all of those modules and the app should build. You'll probably encounter similar errors for eslint-related modules.

```
npm i --save babel-preset-react-hmre
```

(there may be a few others that get thrown after this which will have to be treated similarly)

**Comment by WenXuanYuan** [comment]
Not action 
when I write my code
import { link } from 'react-router'

and in render function when i use <Link></Link>, there will threw error
ERROR in ./src/views/AboutView.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/redbox-react/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views
 @ ./src/views/AboutView.js 28:13-160

ERROR in ./src/views/AboutView.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/react-transform-catch-errors/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views
 @ ./src/views/AboutView.js 32:14-177

ERROR in ./src/views/AboutView.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babel-preset-react-hmre/node_modules/react-transform-hmr/lib/index.js in /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views
 @ ./src/views/AboutView.js 40:14-168

I am fresher in react, what should i do ?

**Comment by git-in-my-anus** [comment]
@WenXuanYuan you are getting this error because of babel caching.
You should either clean your system temp directory (the one returned from node's `os.tmpdir`), or set `cacheDirectory` to `false` in file `build\webpack-environments\_base.js`

**Comment by WenXuanYuan** [comment]
Another error occured:

WARNING in ./src/containers/Root.js

/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/containers/Root.js
  11:3  error  Parsing error: A semicolon is required after a class property

✖ 1 problem (1 error, 0 warnings)


WARNING in ./src/views/HomeView.js

/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views/HomeView.js
  21:3  error  Parsing error: A semicolon is required after a class property

✖ 1 problem (1 error, 0 warnings)


ERROR in ./src/containers/Root.js
Module build failed: SyntaxError: /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/containers/Root.js: A semicolon is required after a class property (11:2)
   9 |   }
  10 | 
> 11 |   get content () {
     |   ^
  12 |     return (
  13 |       <Router history={this.props.history}>
  14 |         {this.props.routes}
    at Parser.pp.raise (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:1413:13)
    at Parser.pp.parseClassProperty (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:2565:10)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3774:20)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3774:20)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3774:20)
    at Parser.parseClassProperty (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3774:20)
    at Parser.pp.parseClassBody (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:2470:34)
    at Parser.pp.parseClass (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:2413:8)
    at Parser.pp.parseExport (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:2630:19)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3625:20)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3625:20)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3625:20)
    at Parser.parseExport (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3625:20)
    at Parser.pp.parseStatement (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:1916:90)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3563:22)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3563:22)
 @ ./src/main.js 11:12-40

ERROR in ./src/views/HomeView.js
Module build failed: SyntaxError: /Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/src/views/HomeView.js: A semicolon is required after a class property (21:2)
  19 |   }
  20 | 
> 21 |   render () {
     |   ^
  22 |     return (
  23 |       <div className='container text-center'>
  24 |         <h1>Welcome to the React Redux Starter Kit</h1>
    at Parser.pp.raise (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:1413:13)
    at Parser.pp.parseClassProperty (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:2565:10)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3774:20)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3774:20)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3774:20)
    at Parser.parseClassProperty (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3774:20)
    at Parser.pp.parseClassBody (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:2470:34)
    at Parser.pp.parseClass (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:2413:8)
    at Parser.pp.parseStatement (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:1877:19)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3563:22)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3563:22)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3563:22)
    at Parser.parseStatement (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3563:22)
    at Parser.pp.parseExportDeclaration (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:2654:15)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3656:22)
    at Parser.<anonymous> (/Users/wen/Documents/SDE/Study/redux/react-redux-starter-kit/node_modules/babylon/index.js:3656:22)
 @ ./src/routes/index.js 13:16-41
webpack: bundle is now VALID.

What should i do ?

**Comment by bradbirnbaum** [comment]
This is based on a new package that came down - we are seeing it in our
code as well.   You need a semi-colon after the statics

**Comment by WenXuanYuan** [comment]
Worked , Thank you !
