### ISSUE TITLE
Static Files

### ISSUE THREAD

**Issue by neiled** [davezuko/react-redux-starter-kit#430]
Hi,

I'm sure I'm doing something stupid here, but referencing an image from the static folder is showing me a warning:
```
Warning: a promise was created in a handler but was not returned from it
    at Object.eval (eval at <anonymous> (/Users/Edwards/dev/js/react/lemons/node_modules/thenify/index.js:30:15), <anonymous>:9:8)
    at /Users/Edwards/dev/js/react/lemons/node_modules/koa-send/index.js:77:28
    at [object Generator].next (native)
    at onFulfilled (/Users/Edwards/dev/js/react/lemons/node_modules/co/index.js:65:19)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at next (/Users/Edwards/dev/js/react/lemons/node_modules/co/index.js:100:51)
    at onFulfilled (/Users/Edwards/dev/js/react/lemons/node_modules/co/index.js:69:7)
    at /Users/Edwards/dev/js/react/lemons/node_modules/co/index.js:54:5
    at co (/Users/Edwards/dev/js/react/lemons/node_modules/co/index.js:50:10)
    at send (/Users/Edwards/dev/js/react/lemons/node_modules/koa-send/index.js:36:10)
    at Object.serve (/Users/Edwards/dev/js/react/lemons/node_modules/koa-static/index.js:41:19)
    at [object Generator].next (native)
    at onFulfilled (/Users/Edwards/dev/js/react/lemons/node_modules/co/index.js:65:19)
    at /Users/Edwards/dev/js/react/lemons/node_modules/co/index.js:54:5
    at Object.co (/Users/Edwards/dev/js/react/lemons/node_modules/co/index.js:50:10)
    at converted (/Users/Edwards/dev/js/react/lemons/node_modules/koa-convert/index.js:17:15)
    at dispatch (/Users/Edwards/dev/js/react/lemons/node_modules/koa-compose/index.js:41:32)
    at next (/Users/Edwards/dev/js/react/lemons/node_modules/koa-compose/index.js:42:18)
    at _callee$ (webpack-hmr.js:15:13)
    at tryCatch (/Users/Edwards/dev/js/react/lemons/node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Edwards/dev/js/react/lemons/node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Edwards/dev/js/react/lemons/node_modules/babel-runtime/regenerator/runtime.js:121:21)
    at step (/Users/Edwards/dev/js/react/lemons/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/Edwards/dev/js/react/lemons/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

I'm just referencing the image by doing ```<img/>``` tags. Nothing special.

Thanks for any help.

p.s.
Just in case anyone else is getting this error and wants to temporarily 'hide them' then just add this to your .env

    BLUEBIRD_WARNINGS=0

**Comment by thangngoc89** [comment]
That's is Koa issue. https://github.com/koajs/koa/issues/607

**Comment by davezuko** [comment]
I will probably silence these (ugh...) for the time being and add a backlog issue to investigate it further. :/

**Comment by davezuko** [comment]
Temporarily silenced these warnings: https://github.com/davezuko/react-redux-starter-kit/commit/401bc154b8e1ff4123cde60563c82ba8b684b66a

Added a backlog task to 2.0.0 roadmap to revisit this. I'll leave the other issue open for the time being
