### ISSUE TITLE
Build failing on npm start

### ISSUE THREAD

**Issue by zlwaterfield** [davezuko/react-redux-starter-kit#517]
Just cloned repo and it throwing this error when running `npm start` (and other npm commands)
 - `npm install` was successful
 - `package.json` is valid json
 - can't see any issues with `./src/main.js`

Any ideas why?

```
ERROR in ./src/main.js
Module build failed: SyntaxError: Cannot read config file: /package.json
Error: /package.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:450:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at loadPackageJSONConfigFile (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint/lib/config/config-file.js:150:16)
    at loadConfigFile (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint/lib/config/config-file.js:194:30)
    at Object.load (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint/lib/config/config-file.js:385:18)
    at loadConfig (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint/lib/config.js:74:33)
    at getLocalConfig (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint/lib/config.js:177:23)
    at Config.getConfig (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint/lib/config.js:272:22)
    at processText (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint/lib/cli-engine.js:203:27)
    at CLIEngine.executeOnText (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint/lib/cli-engine.js:686:26)
    at lint (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint-loader/index.js:25:20)
    at Object.module.exports (/Users/zlwaterfield/Documents/Programming/react-redux-starter-kit/node_modules/eslint-loader/index.js:112:3)
 @ multi app
```

**Comment by zlwaterfield** [comment]
Found issue, it was reading an empty `package.json` from the my root :/
