### ISSUE TITLE
Cannot find module 'iconv-lite'

### ISSUE THREAD

**Issue by coryhouse** [davezuko/react-redux-starter-kit#532]
`npm start` fails with the following;

| => npm start

> react-redux-starter-kit@1.0.0 start /Users/coryhouse/Desktop/test projects/react-redux-starter-kit
> better-npm-run start

running better-npm-run in /Users/coryhouse/Desktop/test projects/react-redux-starter-kit
Executing script: start

to be executed: babel-node bin/server 
  app:config Create configuration. +0ms
  app:config Apply environment overrides for NODE_ENV "development". +1ms
  app:webpack:config Create configuration. +1s
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +2ms
module.js:339
    throw err;
    ^

Error: Cannot find module 'iconv-lite'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (webpack-proxy.js:7:13)
    at Module._compile (module.js:435:26)
    at loader (/Users/coryhouse/Desktop/test projects/react-redux-starter-kit/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/coryhouse/Desktop/test projects/react-redux-starter-kit/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/coryhouse/Desktop/test projects/react-redux-starter-kit/server/main.js:39:21)
    at Module._compile (module.js:435:26)
    at loader (/Users/coryhouse/Desktop/test projects/react-redux-starter-kit/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/coryhouse/Desktop/test projects/react-redux-starter-kit/node_modules/babel-register/lib/node.js:144:7)

**Comment by davezuko** [comment]
Very strange, what is your node and npm version? Will try to reproduce locally when I get a chance.

**Comment by coryhouse** [comment]
node 4.2.1
npm 2.14.17

Running on Mac.
Thanks!

**Comment by nathanfriemel** [comment]
I just ran into the same issue.  Looks like `var iconv = require('iconv-lite')` was added to ~/server/middleware/webpack-proxy.js line:7 

Run a `npm install iconv-lite --save` and retry `npm run` for a quick fix and `"iconv-lite": "^0.4.13", ` needs to be added to package.json for everyone else.

**Comment by davezuko** [comment]
Oh god, totally missed that. I will add it as a temporary hot fix.

**Comment by davezuko** [comment]
Added with https://github.com/davezuko/react-redux-starter-kit/commit/42807936ba4e4375edd9dc347a797635c5615d93. This probably popped up once the middleware started being _always_ imported, rather than just when the proxy was enabled (due to the switch to full ES6 imports).
