### ISSUE TITLE
Can't run latest starter-kit

### ISSUE THREAD

**Issue by davidsteinberger** [davezuko/react-redux-starter-kit#666]
I've used the starter-kit back in December and it's a wonderful experience. However I just tried to clone the repo + npm install + npm start and it's then failing with `TypeError: Cannot read property 'indexOf' of undefined`. I tried different node versions and latest npm. Am I missing something?

Details:
OS: OSX 10.10.5, 10.11.3
Node: v4.2.1, v5.1.1, v5.8.0
NPM: 3.3.8, 3.7.3

Note: I've already tried the obvious `rm -rf node_modules && npm cache clear && npm install`.

**Comment by davezuko** [comment]
That's not good, and you're definitely not missing anything. I am not home at the moment but will take a look tomorrow... there haven't been many changes lately so I'm a bit unsure as to _what_ would cause the issue, so if there are any other details you could provide that would be immensely helpful (what OS, exact npm/node versions, full logs/screenshots, etc.).

My only real advice until I can look is to purge your node_modules, `npm cache clean && npm i``, and then see if that happens to help.

**Comment by bschnelle** [comment]
Just ran into the same issue spinning up a new project and I used this starter kit successfully a few weeks ago.  

```
TypeError: Cannot read property 'indexOf' of undefined
      at getFilenameFromUrl (/Users/bschnelle/new/node_modules/webpack-dev-middleware/middleware.js:129:9)
      at webpackDevMiddleware (/Users/bschnelle/new/node_modules/webpack-dev-middleware/middleware.js:174:18)
      at apply-express-middleware.js:10:5
      at new Promise (/Users/bschnelle/new/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
      at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/bschnelle/new/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)
      at applyExpressMiddleware (apply-express-middleware.js:5:10)
      at _callee$ (webpack-dev.js:23:25)
      at tryCatch (/Users/bschnelle/new/node_modules/babel-runtime/regenerator/runtime.js:88:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/bschnelle/new/node_modules/babel-runtime/regenerator/runtime.js:341:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/bschnelle/new/node_modules/babel-runtime/regenerator/runtime.js:121:21)
      at step (/Users/bschnelle/new/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/bschnelle/new/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (/Users/bschnelle/new/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
      at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/Users/bschnelle/new/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)
      at /Users/bschnelle/new/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at koaWebpackDevMiddleware (webpack-dev.js:22:25)
```

**Comment by texel** [comment]
Just ran into this too. I'll try to find a known-good revision and git bisect to figure out where the bug was introduced.

**Comment by bschnelle** [comment]
Looks like the issue has to do with [this](https://github.com/webpack/webpack-dev-middleware/pull/78) merge PR.

**Comment by texel** [comment]
Thanks @bschnelle. Figured it was a dependency since now this fails in the same way all the way back to alpha.0.

I think it would be a good idea to lock dependency versions in package.json down to avoid issue like this...

**Comment by bschnelle** [comment]
Agreed

**Comment by davidsteinberger** [comment]
Thanks @bschnelle! Honestly I don't understand this PR. Is `req.path` guaranteed to be a drop in replacement for `req.url`? IMO, that only makes sense for requests that point to some asset (maybe have query-params appended) and you really want to get the filename only.

**Comment by bschnelle** [comment]
No problem dudes! @texel @davidsteinberger

**Comment by jflayhart** [comment]
Rolling back webpack-dev-middleware to 1.5.1 fixed it for me.

**Comment by davezuko** [comment]
Will lock the version until this is fixed. Thanks for the investigation.

**Comment by davezuko** [comment]
Locked this dependency with https://github.com/davezuko/react-redux-starter-kit/commit/0bde219574933922169e0290a6e5d2fdc6b47d1e. Adding a backlog task to unlock it once the issue is fixed (will comment back here when that's finished).

Thanks @jflayhart @bschnelle @davidsteinberger @texel
