### ISSUE TITLE
Module build failed: SyntaxError: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by emzero** [davezuko/react-redux-starter-kit#679]
I have a `StreamView` view that renders a [Masonry](https://github.com/eiriklv/react-masonry-component) component passing it a collection of a custom component (`MasonryItem`) that is generated as:
```jsx
const gridChildren = this.props.items.map((msg) => {
  return <MasonryItem message={msg} />;
});
```
Then I'm returning the Masonry grid as:

```jsx
return (
  <div>
    <Masonry>
      {gridChildren}
     </Masonry>
  </div>
)
```

I get the following error in the cmd when running `npm start` and the browser shows "Not Found".
```
ERROR in ./src/components/masonry/masonryItem.js
Module build failed: SyntaxError: E:/Desktop/framework-testing/_mine/react-redux-starter-kit/src/components/masonry/masonryItem.js: 'import' and 'export' may only appear at the top level (5:0)
(function() {

import React, { PropTypes } from 'react';
import css from './masonryItem.scss';
import TimeAgo from 'react-timeago';

    at Parser.pp.raise (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:1378:13)
    at Parser.pp.parseStatement (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:1845:16)
    at Parser.parseStatement (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:3507:22)
    at Parser.pp.parseBlockBody (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:2208:21)
    at Parser.pp.parseBlock (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:2189:8)
    at Parser.pp.parseFunctionBody (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:1125:22)
    at Parser.parseFunctionBody (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:3494:20)
    at Parser.pp.parseFunction (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:2320:8)
    at Parser.pp.parseFunctionExpression (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:759:17)
    at Parser.pp.parseExprAtom (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:721:19)
    at Parser.parseExprAtom (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:4305:22)
    at Parser.pp.parseExprSubscripts (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:504:19)
    at Parser.pp.parseMaybeUnary (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:484:19)
    at Parser.pp.parseExprOps (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:415:19)
    at Parser.pp.parseMaybeConditional (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:397:19)
    at Parser.pp.parseMaybeAssign (E:\Desktop\framework-testing\_mine\react-redux-starter-kit\node_modules\babylon\index.js:360:19)
@ ./src/views/StreamView/StreamView.js 54:19-66
```

If I generate the items without using `<MasonryItem>` as:
```jsx
const gridChildren = this.props.items.map((msg) => {
  return (
    <div className='masonryItem' key={msg.id}>
      {msg.body}
    </div>
  );
});
```
it works well. But as soon as I extract the masonryItem markup to a component, it throws that error.

I've read somewhere that it could be caused by `react-hot-loader` but this is using [react-transform-webpack-hmr](https://github.com/gaearon/react-transform-webpack-hmr) right?
Could be the same reason that's causing this error?

**Comment by emzero** [comment]
Nevermind. It works now, even though I don't know why.
