### ISSUE TITLE
start with pm2

### ISSUE THREAD

**Issue by refluxwhw** [davezuko/react-redux-starter-kit#680]
When I clone this kit and start success. But when I want start it with pm2, An error occurred:
```js
PM2 Error: spawn babel-node ENOENT
PM2     at exports._errnoException (util.js:890:11)
PM2     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
PM2     at onErrorNT (internal/child_process.js:348:16)
PM2     at _combinedTickCallback (node.js:383:13)
PM2     at process._tickDomainCallback (node.js:431:11)
```
I have no idea with it. Hope someone help me. Thanks very much.

My start stup:
- `npm install -g pm2`
- write a config file `pm2_config.json`
```js
{
  "apps" : [{
    "name"        : "my-koa",
    "script"      : "bin/server.js",
    "watch"       : false,
    "exec_interpreter" : "babel-node",
    "exec_mode"        : "fork"
  }]
}
```
- `pm2 start pm2_config.json`
```
$ pm2 start pm2_config.json
[PM2] Process launched
┌──────────┬────┬──────┬─────┬─────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status  │ restart │ uptime │ memory │ watching │
├──────────┼────┼──────┼─────┼─────────┼─────────┼────────┼────────┼──────────┤
│ my-koa   │ 0  │ fork │ N/A │ errored │ 0       │ 0      │ 0 B    │ disabled │
└──────────┴────┴──────┴─────┴─────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```
- `pm2 logs ` the error information as above

**Comment by yansenarmandau** [comment]
have you install babel-node as global?
`{
  "apps" : [{
    "name"        : "server",
    "script"      : "./bin/server.js",
    "watch"       : true,
    "exec_interpreter" : "./node_modules/.bin/babel-node",
        "env": {
                "NODE_ENV": "production"
            },
    "exec_mode"        : "fork",
  }]
}
`
thats my pm2 configuration for production, and working for me

**Comment by refluxwhw** [comment]
yes, i did it.  and `npm start` is work.
and `./node_modules/.bin/babel-node` is there, use your configuration, but it does not work. 
error message:
```
PM2 Starting execution sequence in -fork mode- for app name:my-koa id:0
PM2 App name:my-koa id:0 online
PM2 Error: spawn ./node_modules/.bin/babel-node ENOENT
PM2     at exports._errnoException (util.js:890:11)
PM2     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
PM2     at onErrorNT (internal/child_process.js:348:16)
PM2     at _combinedTickCallback (node.js:383:13)
PM2     at process._tickDomainCallback (node.js:431:11)
```
i did not modify any file, just clone it and run `npm install`. have you modify any file?

**Comment by yansenarmandau** [comment]
yea i do, modify using express server. but i try to re-clone this starter kit and run using npm still working
yansens-MacBook-Pro:react-redux-starter-kit yansen$ pm2 list
```
yansens-MacBook-Pro:react-redux-starter-kit yansen$ pm2 list
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ memory      │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────────────┼──────────┤
│ server   │ 0  │ fork │ 9146 │ online │ 0       │ 10s    │ 19.563 MB   │  enabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```
and when i hit localhost:3000, work perfectly

pm2 configuration : 
```
{
  "apps" : [{
    "name"        : "server",
    "script"      : "./bin/server.js",
    "watch"       : true,
    "exec_interpreter" : "./node_modules/.bin/babel-node",
        "env": {
                "NODE_ENV": "development"
            },
    "exec_mode"        : "fork",
  }]
}
```

**Comment by davezuko** [comment]
Closing per @yansenarmandau 's comments, and this isn't an issue with the starter kit itself. If you're still having trouble I suggest checking out the gitter channel, thanks!
