### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by AlexGrs** [davezuko/react-redux-starter-kit#718]
I'm trying to start to spin this startup kit but i'm stuck with the following error. Do you have any idea what's going on there ?
```
(central)➜  react-redux-starter-kit git:(master) ✗ npm start

> react-redux-starter-kit@2.0.0-alpha.4 start /Users/alexgrs/Work/tutos/react/react-redux-starter-kit
> better-npm-run start

running better-npm-run in /Users/alexgrs/Work/tutos/react/react-redux-starter-kit
Executing script: start

to be executed: babel-node bin/server


  app:config Create configuration. +0ms
  app:config Apply environment overrides for NODE_ENV "development". +2ms
/Users/alexgrs/Work/tutos/react/react-redux-starter-kit/node_modules/koa/lib/application.js:8
const isGeneratorFunction = require('is-generator-function');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alexgrs/Work/tutos/react/react-redux-starter-kit/node_modules/babel-register/lib/node.js:134:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (main.js:1:1)
    at Module._compile (module.js:460:26)

npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@2.0.0-alpha.4 start: `better-npm-run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@2.0.0-alpha.4 start script 'better-npm-run start'.
npm ERR! This is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run start
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alexgrs/Work/tutos/react/react-redux-starter-kit/npm-debug.log
```

**Comment by AlexGrs** [comment]
Never mind, i was running an outdated version of node. Updating it made the trick.
