### ISSUE TITLE
npm start command doesn't work

### ISSUE THREAD

**Issue by IvanYurchenko** [davezuko/react-redux-starter-kit#748]
I've tried to run **npm start** command and faced an error:

```
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/bin/node" "/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3

npm ERR! missing script: start
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ivanyurchenko/npm-debug.log
```

I've found a solution on StackOverflow which tells to add a line to the package.json file:
http://stackoverflow.com/a/31976870

Now I'm starting to run **npm start** and getting the error (which is pretty logically as I didn't create any your-script.js files).

log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/bin/node',
1 verbose cli   '/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose config Skipping project config: /Users/ivanyurchenko/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle ivanyurchenko@1.0.0~prestart: ivanyurchenko@1.0.0
7 silly lifecycle ivanyurchenko@1.0.0~prestart: no script for prestart, continuing
8 info lifecycle ivanyurchenko@1.0.0~start: ivanyurchenko@1.0.0
9 verbose lifecycle ivanyurchenko@1.0.0~start: unsafe-perm in lifecycle true
10 verbose lifecycle ivanyurchenko@1.0.0~start: PATH: /Users/ivanyurchenko/.nvm/versions/node/v5.10.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/ivanyurchenko/node_modules/.bin:/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/bin:/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/bin:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
11 verbose lifecycle ivanyurchenko@1.0.0~start: CWD: /Users/ivanyurchenko
12 silly lifecycle ivanyurchenko@1.0.0~start: Args: [ '-c', 'node your-script.js' ]
13 silly lifecycle ivanyurchenko@1.0.0~start: Returned: code: 1  signal: null
14 info lifecycle ivanyurchenko@1.0.0~start: Failed to exec start script
15 verbose stack Error: ivanyurchenko@1.0.0 start: `node your-script.js`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
15 verbose stack     at emitTwo (events.js:100:13)
15 verbose stack     at EventEmitter.emit (events.js:185:7)
15 verbose stack     at ChildProcess.<anonymous> (/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
15 verbose stack     at emitTwo (events.js:100:13)
15 verbose stack     at ChildProcess.emit (events.js:185:7)
15 verbose stack     at maybeClose (internal/child_process.js:850:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
16 verbose pkgid ivanyurchenko@1.0.0
17 verbose cwd /Users/ivanyurchenko
18 error Darwin 15.4.0
19 error argv "/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/bin/node" "/Users/ivanyurchenko/.nvm/versions/node/v5.10.1/bin/npm" "start"
20 error node v5.10.1
21 error npm  v3.8.3
22 error code ELIFECYCLE
23 error ivanyurchenko@1.0.0 start: `node your-script.js`
23 error Exit status 1
24 error Failed at the ivanyurchenko@1.0.0 start script 'node your-script.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the ivanyurchenko package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node your-script.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs ivanyurchenko
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls ivanyurchenko
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

The problem is I can't run **npm start**. I've tried reinstalling it, updating, upgrading and clearing cache. Also restarted everything include my Mac - didn't work either.

**Comment by davezuko** [comment]
That really doesn't make any sense because there _is_ a start command. I don't have anything else useful to add at the moment, but I'll keep thinking about it...

**Comment by git-in-my-anus** [comment]
From the logs it seems that you are not in the project directory, but in the home dir.

**Comment by IvanYurchenko** [comment]
Running from a wrong directory was a problem in this case, thanks. I think it would be cool to see an informative exception that would tell user to switch the folder. Anyway, at least I've got what caused the issue so I'm closing it.
