### ISSUE TITLE
Problem running starter kit on os-x

### ISSUE THREAD

**Issue by maticrivo** [davezuko/react-redux-starter-kit#770]
node version: 6.0.0
npm version: 3.8.8

after running `npm install` trying to run `npm run dev` return the following error:
(tested both on master and on new-project-v3)
```
$ npm run dev

> react-redux-starter-kit@3.0.0-alpha.0 dev /Users/###/projects/###
> better-npm-run dev

running better-npm-run in /Users/###/projects/###
module.js:440
    throw err;
    ^

Error: Cannot find module './lib/exec.js'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/###/projects/###/node_modules/.bin/better-npm-run:7:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.0.0/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@3.0.0-alpha.0 dev: `better-npm-run dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@3.0.0-alpha.0 dev script 'better-npm-run dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/###/projects/neura/###/npm-debug.log
```

**Comment by davezuko** [comment]
Node 6 just came out so there are likely to be issues unrelated to the starter kit itself. We just merged a PR that bumps the minimum allowed version of node-sass to `^3.7.0`, so if you could update your module accordingly and give it another shot that would be great.

**Comment by davezuko** [comment]
Moving discussion to https://github.com/davezuko/react-redux-starter-kit/issues/772 for node 6.
