### ISSUE TITLE
"npm start" fails: "babel-node bin/server" - Unexpected reserved word

### ISSUE THREAD

**Issue by superKalo** [davezuko/react-redux-starter-kit#818]
Hi,

I am having an issue and I can not run the project. I followed the [getting started docs](https://github.com/davezuko/react-redux-starter-kit#getting-started). I did `npm install` but then when I go for `npm start` it fails with this output:

```bash
> react-redux-starter-kit@3.0.0-alpha.0 start /Users/superkalo/Sites/my-awesome-project
> better-npm-run start

running better-npm-run in /Users/superkalo/Sites/my-awesome-project
Executing script: start

to be executed: babel-node bin/server
/Users/superkalo/Sites/my-awesome-project/bin/server.js:1
(function (exports, require, module, __filename, __dirname) { import config from '../config';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/Users/superkalo/Sites/my-awesome-project/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/superkalo/Sites/my-awesome-project/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at /Users/superkalo/Sites/my-awesome-project/node_modules/babel-cli/lib/_babel-node.js:171:48
    at Object.<anonymous> (/Users/superkalo/Sites/my-awesome-project/node_modules/babel-cli/lib/_babel-node.js:172:7)
    at Module._compile (module.js:409:26)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v3.9.0
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@3.0.0-alpha.0 start: `better-npm-run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-redux-starter-kit@3.0.0-alpha.0 start script 'better-npm-run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-redux-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/superkalo/Sites/my-awesome-project/npm-debug.log
```

I'm on OS X El Capitan with:
node -v: v4.4.4
npm -v: 3.9.0

Hm, am I missing something?

**Comment by davezuko** [comment]
Make sure you do not have a `.babelrc` file in any parent directory, since that can cause conflicts. Every time this issue has come up that's what it's been, so give it a look.

**Comment by superKalo** [comment]
Ahhh, yes, the `.babelrc` was missing. Thank you @davezuko !
