### ISSUE TITLE
`npm run lint` fails

### ISSUE THREAD

**Issue by Kein1945** [davezuko/react-redux-starter-kit#838]
I use master branch and get error with `npm run lint`:
```
$ npm run lint
// ...
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at getStarToken (/code/js/react-redux-starter-kit/node_modules/eslint/lib/rules/generator-star-spacing.js:68:25)
    at EventEmitter.checkFunction (/code/js/react-redux-starter-kit/node_modules/eslint/lib/rules/generator-star-spacing.js:123:29)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/code/js/react-redux-starter-kit/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/code/js/react-redux-starter-kit/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/code/js/react-redux-starter-kit/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/code/js/react-redux-starter-kit/node_modules/eslint/lib/eslint.js:905:36)
    at Controller.__execute (/code/js/react-redux-starter-kit/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/code/js/react-redux-starter-kit/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
```

**Comment by Kein1945** [comment]
ops. I have node v.6.2.0, not like in requirements node ^4.2.0. How I can delete issue?

**Comment by mladen107** [comment]
+1

**Comment by rodneyrd** [comment]
+1
I am actually running through the same issue even though I downgrade to node 4.2.1

**Comment by davezuko** [comment]
Must be new, I wonder if there was a breaking change in one of our dependencies. Will dive into it later.

**Comment by nrakic90** [comment]
+1
On node v6.2.0

**Comment by davezuko** [comment]
ESLint issue for reference: https://github.com/eslint/eslint/issues/6274

**Comment by davezuko** [comment]
Fixed with https://github.com/davezuko/react-redux-starter-kit/commit/28f55d7a0e94c6854ec6a90baf5d2cf676fdba2b.

**Comment by rodneyrd** [comment]
thanks!

**Comment by kodermax** [comment]
It's work. Thanks.
