### ISSUE TITLE
Moving an existing redux project to a different location

### ISSUE THREAD

**Issue by woniesong92** [davezuko/react-redux-starter-kit#865]
The kit works fine after a fresh init, but if you try to move it to a different directory (without `node_modules` and `dist` folders), it crashes with the following error. More specifically, the command `npm run deploy:prod` fails. Any ideas?

```

> react-redux-starter-kit@2.0.0-alpha.4 compile /Users/projFolder
> better-npm-run compile

running better-npm-run in /Users/projFolder
Executing script: compile

to be executed: babel-node bin/compile
/Users/projFolder/node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
      ^

SyntaxError: /Users/projFolder/bin/compile.js: Unexpected token (10:8)
   8 | const paths = config.utils_paths
   9 |
> 10 | ;(async function () {
     |         ^
  11 |   try {
  12 |     debug('Run compiler')
  13 |     const stats = await webpackCompiler(webpackConfig)
    at Parser.pp.raise (/Users/projFolder/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/projFolder/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.expect (/Users/projFolder/node_modules/babylon/lib/parser/util.js:83:33)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/projFolder/node_modules/babylon/lib/parser/expression.js:576:12)
    at Parser.pp.parseExprAtom (/Users/projFolder/node_modules/babylon/lib/parser/expression.js:476:19)
    at Parser.pp.parseExprSubscripts (/Users/projFolder/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/Users/projFolder/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/Users/projFolder/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/Users/projFolder/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/Users/projFolder/node_modules/babylon/lib/parser/expression.js:128:19)t

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy:prod' ]
2 info using npm@3.8.6
3 info using node@v5.11.0
4 verbose run-script [ 'predeploy:prod', 'deploy:prod', 'postdeploy:prod' ]
5 info lifecycle react-redux-starter-kit@2.0.0-alpha.4~predeploy:prod: react-redux-starter-kit@2.0.0-alpha.4
6 silly lifecycle react-redux-starter-kit@2.0.0-alpha.4~predeploy:prod: no script for predeploy:prod, continuing
7 info lifecycle react-redux-starter-kit@2.0.0-alpha.4~deploy:prod: react-redux-starter-kit@2.0.0-alpha.4
8 verbose lifecycle react-redux-starter-kit@2.0.0-alpha.4~deploy:prod: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter-kit@2.0.0-alpha.4~deploy:prod: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/user/proj/node_modules/.bin:/usr/local/bin:/Users/user/.rbenv/shims:/Users/user/.opam/system/bin:/Users/user/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle react-redux-starter-kit@2.0.0-alpha.4~deploy:prod: CWD: /Users/user/proj
11 silly lifecycle react-redux-starter-kit@2.0.0-alpha.4~deploy:prod: Args: [ '-c', 'better-npm-run deploy:prod' ]
12 silly lifecycle react-redux-starter-kit@2.0.0-alpha.4~deploy:prod: Returned: code: 1  signal: null
13 info lifecycle react-redux-starter-kit@2.0.0-alpha.4~deploy:prod: Failed to exec deploy:prod script
14 verbose stack Error: react-redux-starter-kit@2.0.0-alpha.4 deploy:prod: `better-npm-run deploy:prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid react-redux-starter-kit@2.0.0-alpha.4
16 verbose cwd /Users/user/proj
17 error Darwin 15.2.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy:prod"
19 error node v5.11.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error react-redux-starter-kit@2.0.0-alpha.4 deploy:prod: `better-npm-run deploy:prod`
22 error Exit status 1
23 error Failed at the react-redux-starter-kit@2.0.0-alpha.4 deploy:prod script 'better-npm-run deploy:prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     better-npm-run deploy:prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Also, for a different command:

```
$ npm start

> react-redux-starter-kit@2.0.0-alpha.4 start project
> better-npm-run start

running better-npm-run in project
Executing script: start

to be executed: babel-node bin/server
project/bin/server.js:1
(function (exports, require, module, __filename, __dirname) { import config from '../config';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (project/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (project/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at project/node_modules/babel-cli/lib/_babel-node.js:160:24
    at Object.<anonymous> (project/node_modules/babel-cli/lib/_babel-node.js:161:7)
    at Module._compile (module.js:413:34)
```

It looks like suddenly ES6 syntax doesn't work.

**Comment by Aourin** [comment]
Do you simply mean, that you are just copy the folder or moving the dir somewhere (excluding the node_modules and dist folder) and rerunning npm install after?

**Comment by woniesong92** [comment]
To reproduce the issue, try the following.

1. Start from a fresh redux project.
2. Run `npm install`.
3. Remove `dist/`.
4. Move the entire folder to a different location.
5. Running `npm install & npm run start` fails.

I am puzzled that deleting `dist/` folder results in the app breaking.

**Comment by davezuko** [comment]
Is there a conflicting `.babelrc` in the directory you've moved to (or in a parent directory)?

**Comment by davezuko** [comment]
Also might I just add that I'm very confused as to _why_ you're doing this? Is this not the same thing as just cloning it into a different directory?

**Comment by woniesong92** [comment]
@davezuko I will close this for now since I resolved the problem by not removing `dist` folder before moving the directory. I am still unsure why that solves the problem..

I had a redux app inside `frontend/` under my main app. I wanted to move it away to give it an independent repository.
