### ISSUE TITLE
npm run server:start and npm run start

### ISSUE THREAD

**Issue by Casedy** [davezuko/react-redux-starter-kit#98]
after update till `0.14.0` there are problems.

In dev server warning:
`Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.`

In production.

`npm run compile --production`
`npm run server:start`

```
> react-redux-starter-kit@0.14.0 server:start react-redux-starter-kit
> node --harmony bin/server

fs.js:783
  binding.stat(pathModule._makeLong(path), req);
          ^
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.stat (fs.js:783:11)
    at Object.<anonymous> (react-redux-starter-kit/consul/index.js:8:4)
    at Module._compile (module.js:460:26)
    at normalLoader (react-redux-starter-kit/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (react-redux-starter-kit/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by davezuko** [comment]
The `findDOMNode` warning is from redux-devtools, so hopefully that package will be updated soon. As far as the other issue... not really sure what's causing that. Is this from a freshly cloned repo?

**Comment by Casedy** [comment]
sorry, it's my changes for consul ))
all fine.
