### ISSUE TITLE
npm run dev crashes

### ISSUE THREAD

**Issue by kimispencer** [davezuko/react-redux-starter-kit#996]
Not sure why this crash started happening.

    > express-react-redux-starter@1.0.0 dev /Users/unomas/Documents/web/suited-template
	> webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors

	events.js:141
	      throw er; // Unhandled 'error' event
	      ^

	Error: listen EADDRINUSE 127.0.0.1:3000
	    at Object.exports._errnoException (util.js:907:11)
	    at exports._exceptionWithHostPort (util.js:930:20)
	    at Server._listen2 (net.js:1250:14)
	    at listen (net.js:1286:10)
	    at net.js:1395:9
	    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:64:16)
	    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:83:10)

	npm ERR! Darwin 14.5.0
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
	npm ERR! node v4.5.0
	npm ERR! npm  v2.15.9
	npm ERR! code ELIFECYCLE
	npm ERR! express-react-redux-starter@1.0.0 dev: `webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the express-react-redux-starter@1.0.0 dev script 'webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors'.
	npm ERR! This is most likely a problem with the express-react-redux-starter package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs express-react-redux-starter
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR! 
	npm ERR!     npm owner ls express-react-redux-starter
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /Users/unomas/Documents/web/suited-template/npm-debug.log

npm-debug.log

    0 info it worked if it ends with ok
	1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
	2 info using npm@2.15.9
	3 info using node@v4.5.0
	4 verbose run-script [ 'predev', 'dev', 'postdev' ]
	5 info predev express-react-redux-starter@1.0.0
	6 info dev express-react-redux-starter@1.0.0
	7 verbose unsafe-perm in lifecycle true
	8 info express-react-redux-starter@1.0.0 Failed to exec dev script
	9 verbose stack Error: express-react-redux-starter@1.0.0 dev: `webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors`
	9 verbose stack Exit status 1
	9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
	9 verbose stack     at emitTwo (events.js:87:13)
	9 verbose stack     at EventEmitter.emit (events.js:172:7)
	9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
	9 verbose stack     at emitTwo (events.js:87:13)
	9 verbose stack     at ChildProcess.emit (events.js:172:7)
	9 verbose stack     at maybeClose (internal/child_process.js:829:16)
	9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
	10 verbose pkgid express-react-redux-starter@1.0.0
	11 verbose cwd /Users/unomas/Documents/web/suited-template
	12 error Darwin 14.5.0
	13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
	14 error node v4.5.0
	15 error npm  v2.15.9
	16 error code ELIFECYCLE
	17 error express-react-redux-starter@1.0.0 dev: `webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors`
	17 error Exit status 1
	18 error Failed at the express-react-redux-starter@1.0.0 dev script 'webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors'.
	18 error This is most likely a problem with the express-react-redux-starter package,
	18 error not with npm itself.
	18 error Tell the author that this fails on your system:
	18 error     webpack-dev-server --config ./webpack/webpack-dev.config.js --watch --colors
	18 error You can get information on how to open an issue for this project with:
	18 error     npm bugs express-react-redux-starter
	18 error Or if that isn't available, you can get their info via:
	18 error
	18 error     npm owner ls express-react-redux-starter
	18 error There is likely additional logging output above.
	19 verbose exit [ 1, true ]

**Comment by kimispencer** [comment]
Sorry, it's late. This is the wrong Git repo for this template.
